# Generated by Django 5.1 on 2024-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100)),
                ('PRDDescription', models.TextField(max_length=200)),
                ('PRDPrice', models.DecimalField(decimal_places=3, max_digits=5)),
                ('PRDCost', models.DecimalField(decimal_places=3, max_digits=5)),
                ('PRDCreated', models.DateTimeField()),
            ],
        ),
    ]
