# Generated by Django 5.1 on 2024-09-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_catdescription_category_catimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATSParent',
        ),
        migrations.AddField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
