# Generated by Django 5.1 on 2024-09-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_options_alter_category_catparent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDescription',
            field=models.TextField(max_length=200, verbose_name='Product Description'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='Product Name')),
                ('PACClternatives', models.ManyToManyField(blank=True, related_name='accessories_product', to='product.product', verbose_name='Alternatives Product Name')),
            ],
            options={
                'verbose_name': 'Product Accessories',
                'verbose_name_plural': 'Product Accessoriess',
            },
        ),
    ]
