# Generated by Django 5.1 on 2024-09-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_alternative_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDescription',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImage',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACClternatives',
            field=models.ManyToManyField(blank=True, related_name='accessories_product', to='product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternatives',
            field=models.ManyToManyField(blank=True, related_name='alternatives_product', to='product.product', verbose_name='Alternative'),
        ),
    ]
