# Generated by Django 5.1 on 2024-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_accessories_pacclternatives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_accessories',
            name='PACClternatives',
            field=models.ManyToManyField(blank=True, related_name='accessories_product', to='product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALNAlternatives',
            field=models.ManyToManyField(blank=True, related_name='alternatives_product', to='product.product', verbose_name='Alternative'),
        ),
    ]
