# Generated by Django 5.1 on 2024-09-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_accessories_pacclternatives_and_more'),
        ('settings', '0003_brand_delete_prand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='PRDPrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prand_product', to='settings.brand', verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDVariant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_product', to='settings.variant', verbose_name='Variant Name'),
        ),
    ]
