# Generated by Django 5.1 on 2024-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prdcategory_product_prdprand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDVariant',
        ),
    ]
