# Generated by Django 5.1 on 2024-09-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_prdimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_accessories',
            old_name='PACClternatives',
            new_name='PACCAccessories',
        ),
    ]
