# Generated by Django 5.1 on 2024-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_pacclternatives_product_accessories_paccaccessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
