# Generated by Django 5.1 on 2024-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_options_product_prddiscountprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIs_BestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIs_New',
            field=models.BooleanField(default=True),
        ),
    ]
