# Generated by Django 5.1 on 2024-09-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_prdis_bestseller_product_prdis_new'),
        ('settings', '0003_brand_delete_prand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDPrand',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='settings.brand', verbose_name='Brand Name'),
        ),
    ]
