# Generated by Django 5.1 on 2024-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_prand_prddescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=50, verbose_name='Brand Name')),
                ('PRDDescription', models.TextField(blank=True, null=True, verbose_name='Brand Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.DeleteModel(
            name='Prand',
        ),
    ]
